### ISSUE TITLE
AmazonSQS#receiveMessage cleanup entire queue

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [adamw/elasticmq#103]
Start server and try to store **1** message via AmazonSQS. Then call `com.amazonaws.services.sqs.AmazonSQS#receiveMessage(java.lang.String)` twice. On secod call you will see no messages. From my opinion it is a bug, because amazon do not delete messages when they are received.

**Comment by adamw** [comment]
But messages are blocked until the visibility timeout passes. Do you see different behavior when using SQS and when using ElasticMQ?

**Comment by C-h-e-r-r-y** [comment]
Sorry I forgot about timeout. No there is no any different behaviour to spot.
