### ISSUE TITLE
Deadletter Queues Should Be Assigned By ARN, not name.

### ISSUE THREAD

**Issue by AjayTripathy** [adamw/elasticmq#109]
I was able to create a deadletterqueue like this using boto3:
```
    def GetOrCreateQueue(self, queue_name):
        """Gets or creates a queue and a corresponding deadletter queue"""
        deadletter_queue_name = queue_name + '_deadletter'
        dlq = self.sqs_resource.create_queue(QueueName=deadletter_queue_name)
        redrive_policy = {
            'deadLetterTargetArn': queue_name + '_deadletter',
            'maxReceiveCount': 1
        }
        return self.sqs_resource.create_queue(QueueName=queue_name, Attributes={'RedrivePolicy': json.dumps(redrive_policy)})
```

But this is actually a small deviation from the sqs API-- deadletter queues should be configured by ARN, not name. The code should read:    
```
def GetOrCreateQueue(self, queue_name):
        """Gets or creates a queue and a corresponding deadletter queue"""
        deadletter_queue_name = queue_name + '_deadletter'
        dlq = self.sqs_resource.create_queue(QueueName=deadletter_queue_name)
        redrive_policy = {
            'deadLetterTargetArn': dlq.attributes['QueueArn'],
            'maxReceiveCount': 1
        }
        return self.sqs_resource.create_queue(QueueName=queue_name, Attributes={'RedrivePolicy': json.dumps(redrive_policy)})
```

Am I missing something here? The code on the bottom throws a queue not found exception when trying to create the second queue.

**Comment by AjayTripathy** [comment]
@adamw any thoughts? I could maybe look into the difficulty of doing this if we can agree on what the right thing to do here is?

**Comment by adamw** [comment]
@AjayTripathy you are right of course, that parameter should be the ARN (see http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-dead-letter-queue.html). If you could work on that, that would be great :)

**Comment by zozfried** [comment]
I just ran into this issue too and decided to take care of it. I never worked with scala but i hope that this can be handled with an easy string transformation since redrive policies are only suppoorted for queue creation.
