### ISSUE TITLE
MaxReceiveCount should be a string representation of an int, not an int

### ISSUE THREAD

**Issue by AjayTripathy** [adamw/elasticmq#110]
See: [http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html)

It's surprising and a little unintuitive, but AWS expects a string representation of MaxReceiveCount:

String redrivePolicy = "{\"maxReceiveCount\":\"5\", \"deadLetterTargetArn\":\"arn:aws:sqs:us-east-2:123456789012:MyDeadLetterQueue\"}";

If you try to send a string over to elasticmq, however, elasticmq will complain that it expects an int.

**Comment by adamw** [comment]
Indeed that should be corrected - maybe you could attempt a PR to fix that? :)

**Comment by AjayTripathy** [comment]
Sure. Just wanted to make sure I had this right before starting.
