### ISSUE TITLE
Configure

### ISSUE THREAD

**Issue by Fosol** [adamw/elasticmq#119]
How do you configure elasticmq accessKeyId, secretAccessKey and region?  I keep getting ```InvalidClientTokenId: The security token included in the request is invalid.```

Also what is the default QueueUrl path?  I've included a custom configuration file.
```
queues {
	wcm {
		deadLettersQueue {
			name = "wcm-dead-letters",
			maxReceiveCount = 3
		}
	},
	wcm-dead-letters { }
}
```

**Comment by adamw** [comment]
You can set the access key id and secret key to anything you want, these are not checked. The important part is that you set the endpoint on the AWS client to the address on which ElasticMQ is running. I'm not sure what language you are using, but here's the Java version:

https://github.com/adamw/elasticmq/blob/master/rest/rest-sqs-testing-amazon-java-sdk/src/test/scala/org/elasticmq/rest/sqs/AmazonJavaSdkTestSuite.scala#L51-L52

As for the queue url, you can obtain in using `CreateQueue` or `GetQueueUrl`

**Comment by adamw** [comment]
Ah. Well that's all that you need to do. You only need the access keys on the *client* side - that is when you try to connect to the server. There, you can use any values that you'd like.
