### ISSUE TITLE
Queues not created using java sdk

### ISSUE THREAD

**Issue by willieowens** [adamw/elasticmq#135]
Using gradle as a build system, and having multiple projects which would like to use the same queue, I decided to create another gradle project to start an elasticmq server with.

The build.gradle is as follows:
```dependencies {
    compile 'org.elasticmq:elasticmq-rest-sqs_2.11:0.13.9'
}

apply plugin: 'application'

mainClassName = 'com.wowens.elasticmq.ElasticMqSqs'
applicationDefaultJvmArgs = ['-Dconfig.file=src/main/resources/com/wowens/elasticmq/elasticmq.conf']
```

Pretty simple. There is one class to start the queues, ElasticMqSqs, which is simply:
```package com.wowens.elasticmq;

import org.elasticmq.rest.sqs.SQSRestServerBuilder;

public class ElasticMqSqs {

    public static void main(String[] args) {
        SQSRestServerBuilder.start();
    }
}
```

I have an elasticmq conf file in my resources:
```include classpath("application.conf")

queues {
    Queue1 {
    }
}
```

While the server starts up, it doesn't make a queue for me. If I use the same conf file with the jar directly it does create the queue...

ie.) `java -Dconfig.file=elasticmq.conf -jar ~/Downloads/elasticmq-server-0.13.9.jar`

Any thoughts? It seems to be picking up the conf file, as if I change the name/path it breaks cause it can't be found. If you suspect this may be a gradle-related issue, lmk.

Thanks,
Willie

**Comment by adamw** [comment]
I think this might be gradle-specific, maybe `-Dconfig.file` when specified in `applicationDefaultJvmArgs` doesn't really set the system property?

**Comment by willieowens** [comment]
It's definitely set. I can print it out as the first line in my main() function and get:

config.file: src/main/resources/com/urjanet/ymir/elasticmq/elasticmq.conf

**Comment by adamw** [comment]
ah 🤦‍♂️ sorry, the queues from the config file only get created when you run `org.elasticmq.server.Main` from the `elasticmq-server` project. That's probably why things don't work as expected :)

**Comment by willieowens** [comment]
I was gonna ask if that was the case haha, that makes sense. Thanks!
