### ISSUE TITLE
Setting up a Bazel build

### ISSUE THREAD

**Issue by hsyed** [adamw/elasticmq#139]
We'd like to make use of the fifo support (#125) but until it gets merged into master and released on maven it's quite tedious to depend on. Adding bazel `BUILD` files to the repo would make it a bit easier (for anyone using bazel) to use different branches / commits in an agile fashion. 

I'll probably vendor the fifo branch from @simong in our mono repo and setup a bazel build. This would just be a single or a few`BUILD.bazel` files -- no `WORKSPACE` or  dep management since we have this setup in our mono repo already. 

@adamw Would you accept a PR for a bazel build ?

**Comment by adamw** [comment]
@hsyed I suppose the main question is, would this be useable for anybody outside your organization?

**Comment by hsyed** [comment]
It doesn't seem to be straight forward to provide neutral bazel `BUILD` files for Scala -- the BUILD would have to be fairly elaborate. so I'll close this issue.
