### ISSUE TITLE
Long Polling Requests Fail on FIFO Queues

### ISSUE THREAD

**Issue by chrislbs** [adamw/elasticmq#151]
We're using elasticmq to mock the SQS service for our java application. We're using the Java JMS AWS SDK which uses long polling 'WaitTimeSeconds=20 ' to prefetch messages for processing. We noticed during our tests that the time from message sent -> message received that it would take upwards of 15 seconds (or sometimes not at all) for us to get an answer on FIFO queues but standard queues always seemed pretty snappy e.g. < 1 second. I'm not familiar enough with Scala or Akka to really tackle this issue and understand what's causing the problem but I wrote a test that at least simulates the behavior I'm seeing.

```scala
// THIS TEST FAILS
test("FIFO queues should respond during long polling") {
    // Given
    val createRequest = new CreateQueueRequest(s"testFifoQueue-long-poll.fifo")
      .addAttributesEntry("FifoQueue", "true")
      .addAttributesEntry("ContentBasedDeduplication", "false")

    val queueUrl = client.createQueue(createRequest).getQueueUrl

    val messageRequest = new SendMessageRequest(queueUrl, "Message 1")
      .withMessageGroupId("group1")
      .withMessageDeduplicationId(UUID.randomUUID().toString)

    val longPollRequest = new ReceiveMessageRequest(queueUrl).withWaitTimeSeconds(20);

    var t = new Thread() {
      override def run(): Unit = {
        Thread.sleep(3000L)
        client.sendMessage(messageRequest)
      }
    }
    t.start()

    // When
    var start = System.currentTimeMillis()
    var messages = client.receiveMessage(longPollRequest).getMessages
    var end = System.currentTimeMillis()

    // Then
    (end - start) should be >= 3000L
    (end - start) should be <= 6000L
    messages.size should be(1)

    // run against with same content and group id but different deduplication id
    messageRequest.withMessageDeduplicationId(UUID.randomUUID().toString)

    t = new Thread() {
      override def run(): Unit = {
        Thread.sleep(3000L)
        client.sendMessage(messageRequest)
      }
    }
    t.start()

    // When
    start = System.currentTimeMillis()
    messages = client.receiveMessage(longPollRequest).getMessages
    end = System.currentTimeMillis()

    // Then
    (end - start) should be >= 3000L
    (end - start) should be <= 6000L
    messages.size should be(1)
  }

// THIS TEST PASSES
test("Standard queues has no issue during long polling") {
    // Given

    val createRequest = new CreateQueueRequest("standard-queue-long")
    val queueUrl = client.createQueue(createRequest).getQueueUrl

    val messageRequest = new SendMessageRequest(queueUrl, "Message 1")

    val longPollRequest = new ReceiveMessageRequest(queueUrl).withWaitTimeSeconds(20)

    var t = new Thread() {
      override def run(): Unit = {
        Thread.sleep(3000L)
        client.sendMessage(messageRequest)
      }
    }
    t.start()

    // When
    var start = System.currentTimeMillis()
    var messages = client.receiveMessage(longPollRequest).getMessages
    var end = System.currentTimeMillis()

    // Then
    (end - start) should be >= 3000L
    (end - start) should be <= 6000L
    messages.size should be(1)

    t = new Thread() {
      override def run(): Unit = {
        Thread.sleep(3000L)
        client.sendMessage(messageRequest)
      }
    }
    t.start()

    // When
    start = System.currentTimeMillis()
    messages = client.receiveMessage(longPollRequest).getMessages
    end = System.currentTimeMillis()

    // Then
    (end - start) should be >= 3000L
    (end - start) should be <= 6000L
    messages.size should be(1)
  }
```

**Comment by chrislbs** [comment]
Going to cc @simong as he did most of the original work.

**Comment by kingjerod** [comment]
I'm running into the same problems while using aws-sdk on NodeJS. I'm using SQS-insight to verify what makes it in. I ran a test where I add 10 jobs and then try to retrieve them from the queue in a loop (retrieve job, log message, delete job). I've tried setting the message de-duplication id myself and also using the config option for it, no difference.

Issues I've found:

- Adding 10 jobs to a FIFO queue, usually only the first 1-3 make it in. I don't get any errors while adding them.

- After adding them to the queue, sometimes I cannot pull ANY out. This might not even be a FIFO only problem, as I've tried running the same test with non FIFO queues and sometimes it can only retrieve 7/10 jobs. I still see the remaining jobs with SQS-insight. 

- With short polling, I get no results. With long polling, I sometimes get jobs from the queue but it takes 10+ seconds, even though the queue has 10 jobs in it. 

This is all on version 0.14.5. This test works fine using AWS SQS.

**Comment by chrislbs** [comment]
The test above didn't properly address the issue. It turns out the issue was actually with the behavior of specifying a requestAttemptId with a FIFO queue. I've opend pull request #155 that addresses the issue. I'm not sure if it is the best idiomatic implementation as I don't really know Scala but it was a relatively simple fix once I understood how everything plugged together.

**Comment by chrislbs** [comment]
Closing as #155 resolved the issue and was merged.
