### ISSUE TITLE
"Lastest" tag is not being updated

### ISSUE THREAD

**Issue by roribio** [adamw/elasticmq#156]
Hi,

Big fan of this project 🥇

I've noticed that new versions are being released but not being marked as latest. Is this because the newer versions are not considered stable yet?

The reason I ask is that I've got some automation that looks at the `latest` tag and is triggered to update my builds when a new `latest` is released.

Thanks,
Ronald

**Comment by adamw** [comment]
@roribio Is that on the docker image?

**Comment by roribio** [comment]
@adamw My apologies for not being clearer before, I'm referring to GitHub releases. 

If you go to the [releases](https://github.com/adamw/elasticmq/releases) page, you can see that the tag `release-0.13.8` was promoted to "`Latest release`". After that, new versions have been released but not promoted to "`Latest release`". Coincidentally, that is also the last tag to follow the `release-X.Y.Z` naming pattern.

**Comment by adamw** [comment]
Ah :) TBH, no idea how GH determines the "latest" tag. I've switched to an automated release process which uses a different naming convention for tags, hence the change.

The latest release is definitely 0.14.6

**Comment by adamw** [comment]
Ah, I suppose that's because earlier I used to do "GitHub releases" based on the tag - now it's just a tag.

**Comment by roribio** [comment]
Thanks for pointing me in the right direction. With that I've managed to cobble something together and submit a PR: https://github.com/adamw/elasticmq/pull/157.

**Comment by adamw** [comment]
With some adjustments, seems to work. Thanks!

**Comment by roribio** [comment]
Awesome! Thank you :)
