### ISSUE TITLE
QueueUrl response uses Host header instead of config address

### ISSUE THREAD

**Issue by sthulb** [adamw/elasticmq#18]
Hi,

It would be nice if elasticmq used the Host instead of what's in the config. A case for this is Docker, when using elasticmq in a container, the QueueUrl is almost certainly going to be wrong.

**Comment by TomFrost** [comment]
+1. Same situation with Docker. I'm stuck building my test boxes with ugly /etc/hosts hacks just to get this running without polluting my codebase with test-specific logic.

**Comment by icambron** [comment]
I would be more than happy to write a PR for this if @adamw gives me the go-ahead.

**Comment by adamw** [comment]
Sure, I would be happy to get a PR in for this. Do I understand correctly that this would be a kind of a special setting for `node-address` meaning "return whatever the incoming host was"?

**Comment by icambron** [comment]
Yup, or a different setting. I originally had in mind that it could use `bind-address`, but that might break things for people. How does setting `node-address` to `*` sound?

**Comment by adamw** [comment]
I guess the `node-address` setting makes more sense here as it's the "outside visible" address. `*` sounds good as well :) 

Btw. if you think it would make sense to do some breaking changes, now is a good moment, as I'm preparing a 0.9 release.

**Comment by warrenseymour** [comment]
I had a need for a similar feature when using ElasticMQ in a docker-compose environment, and found this workaround:

```
node-address {
    protocol = http
    host = ${HOSTNAME}
    port = 9324
    context-path = ""
}
```

**Comment by icambron** [comment]
I expected to have some time to do this by now, but haven't gotten the chance.

@warrenseymour - how does that work? Doesn't seem like that would set the queue URL on a per-request basis, but maybe I don't get it.

**Comment by warrenseymour** [comment]
@icambron I only needed the queue URL to exposed as something that was reachable from linked  containers. In this case, the URL doesn't need to be set per-request; boot-time will suffice.

**Comment by icambron** [comment]
@warrenseymour does that address work for both your linked containers and from your host?

**Comment by warrenseymour** [comment]
@icambron Very good point that I had not considered; in my particular case, I have no interest in speaking to ElasticMQ from my host; only from within containers.

For that, I'll guess you'll need roll your sleeves up :)
