### ISSUE TITLE
Support QueueArn attribute

### ISSUE THREAD

**Issue by ddossot** [adamw/elasticmq#36]
It would be great if each queue could have an associated `QueueArn` attribute: that would be ElasticMQ behave more like SQS, allowing code run the same way whether using one or the other as a back-end.

**Comment by adamw** [comment]
To be honest I wasn't aware that this is needed - which calls are broken and in which environment (programming language?)

**Comment by ddossot** [comment]
This is language agnostic.

If you call [GetQueueAttribute](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueAttributes.html), there's no value associated with `QueueArn` in ElasticMQ. If you do the same with SQS, you get a value.

The `QueueArn` is the unique identifier for the queue: we use this value in logging statement, in monitoring and, even more importantly, when subscribing to `SNS`.

**Comment by adamw** [comment]
Ah I see. Yeah this makes sense of course :) Maybe you'd like to try a pull request? Probably would involve changing https://github.com/adamw/elasticmq/blob/master/rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/QueueAttributesDirectives.scala, if no other SQS calls are affected.

**Comment by ddossot** [comment]
No change needed to core, right? Just create this attribute on the fly based on `queueData.name` should do the trick, is that what you have in mind?

And sure, I could try a PR.

**Comment by adamw** [comment]
Yes, creating this on the fly should be good, core most certainly will be unaffected.

**Comment by adamw** [comment]
0.8.6 released. Thanks!
