### ISSUE TITLE
Can't run SBT build

### ISSUE THREAD

**Issue by ddossot** [adamw/elasticmq#37]
Running `sbt clean test` on `master` or `release-0.8.5` fails with:

```
[error] File name too long
[error] one error found
[error] File name too long
[error] one error found
[error] (elasticmq-rest-sqs/compile:compile) Compilation failed
[error] (elasticmq-core/test:compile) Compilation failed
[error] Total time: 42 s, completed 5-Feb-2015 10:29:42 AM
```

Full build transcript here: http://pastebin.com/iwGZH1d0

More info:

```
$ sbt about
[info] Loading project definition from /home/ddossot/dev/scala/libs/elasticmq/project
[info] Set current project to elasticmq-root (in build file:/home/ddossot/dev/scala/libs/elasticmq/)
[warn] Credentials file /home/ddossot/.ivy2/.credentials does not exist
[info] This is sbt 0.13.6
[info] The current project is {file:/home/ddossot/dev/scala/libs/elasticmq/}elasticmq-root 0.8.5
[info] The current project is built against Scala 2.11.4
[info] Available Plugins: sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.CorePlugin, sbt.plugins.JUnitXmlReportPlugin, net.virtualvoid.sbt.graph.Plugin, com.typesafe.sbt.SbtPgp, sbtassembly.Plugin, com.gu.TeamCityTestReporting
[info] sbt, sbt plugins, and build definitions are using Scala 2.10.4
```

**Comment by adamw** [comment]
File name too long hmm ... I wonder which one :) What OS is it? And what filesystem?

**Comment by ddossot** [comment]
OS info:
```
Linux ovonel 3.13.0-34-generic #60-Ubuntu SMP Wed Aug 13 15:45:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

/dev/sda5 on / type ext4 (rw,errors=remount-ro)
```

**Comment by adamw** [comment]
Looks quite normal. I'll try to test this on a Linux somewhere (on macos it works)

**Comment by ddossot** [comment]
OK, let me know if there are any further `sbt` commands I could run.

I can't start working on a PR for issue #36 until I have a working build :crying_cat_face:

**Comment by adamw** [comment]
I'm on a poor hotel-internet so I have a hard time googling :)
One thing I would try is entering the console (`sbt`), then compiling (`compile`), and when it fails, inspecting the details (`last compile`)

**Comment by adamw** [comment]
A friend tested on Ubuntu 14.04/ext4/OpenJDK 1.7.0_75 and works without problems. Which java do you have?

**Comment by ddossot** [comment]
Here you go:
```
$ java -version
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)
```

Also here is the transcript of `compile` and `last compile` in `sbt`: http://pastebin.com/DewDuFaL

Thanks for your support, good luck with the hotel wifi :wink:

**Comment by adamw** [comment]
Some people had this when they cloned the sources into an encrypted home folder (https://github.com/scala/pickling/issues/10)

Can you try adding `scalacOptions ++= Seq("-Xmax-classfile-name", "254")` to `project/Build.scala`, after line 8?

**Comment by ddossot** [comment]
Encryption was the issue: if I checkout the project in `/tmp`, it's all good.

Sorry about that, I should have thought of it :blush:
