### ISSUE TITLE
Instructions to Run From Source

### ISSUE THREAD

**Issue by cancan101** [adamw/elasticmq#42]
I am trying to use `sbt` to run this from source. Within the shell I am running `run` but I get:
```
> run
[warn] Credentials file /Users/alex/.ivy2/.credentials does not exist
java.lang.RuntimeException: No main class detected.
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last elasticmq-root/compile:run for the full output.
[error] (elasticmq-root/compile:run) No main class detected.
[error] Total time: 0 s, completed Feb 23, 2015 12:33:18 PM
```
alternatively, how do I create a JAR like the one posted in the README?

**Comment by adamw** [comment]
You have to switch to the `elasticmq-server` project, which contains the main class. So:
```
> project elasticmq-server
> run
```

or in one command: `elasticmq-server/run`.

To create a fat-jar, you need to run `assembly` also while in the `elasticmq-server` sub-module.

Hope that helps!

**Comment by cancan101** [comment]
Cool, thanks that worked! Might be worth adding these notes to the README.
