### ISSUE TITLE
secure=False required?

### ISSUE THREAD

**Issue by dnephin** [adamw/elasticmq#48]
Hello,

I'm just getting started with elasticmq.  I'm using [boto](http://boto.readthedocs.org/en/latest/index.html#) (the official aws client)  as the client, and I was running into a bunch of errors I didn't understand:

```
[WARN] [05/06/2015 20:36:37.435] [elasticmq-akka.actor.default-dispatcher-51] [akka://elasticmq/user/IO-HTTP/listener-0/23] Illegal request, responding with status '501 Not Implemented': Unsupported HTTP method
```

I was able to get it working by setting `is_secure=False` in boto (it defaults to `is_secure=True`).

I didn't see anything in the README about secure=False, or SSL.  Is this expected? Is there some way to get it to work with secure?  If not, could you add a note to the docs somewhere about that?

Thanks!

**Comment by cancan101** [comment]
I use this with boto and it works fine:
```python

region = boto.sqs.regioninfo.RegionInfo(name='elasticmq',
                                        endpoint=sqs_endpoint)
conn = boto.connect_sqs(aws_access_key_id='x',
                        aws_secret_access_key='x',
                        is_secure=False,
                        port=sqs_port,
                        region=region)

```

**Comment by adamw** [comment]
ElasticMQ exposes the API via HTTP, so it doesn't handle https in any way (would be quite complex given that you would have to provide certificates etc).

If you could make a PR with README changes describing how to use EMQ from Boto (I never used that :) ), it would be great!

**Comment by dnephin** [comment]
Cool, #49 looks good. It doesn't explicitly call out `is_secure=False` in the text, but the example should do.

Thanks!
