### ISSUE TITLE
java.lang.NoClassDefFoundError: shapeless/HListerAux

### ISSUE THREAD

**Issue by spiritedtechie** [adamw/elasticmq#51]
elasticmq version: 0.8.8

Not sure if this is an issue and I cannot see anything obviously wrong with my dependencies. I am getting the following exception:

java.lang.NoClassDefFoundError: shapeless/HListerAux$
	at org.elasticmq.rest.sqs.directives.ElasticMQDirectives$class.action(ElasticMQDirectives.scala:24)
	at org.elasticmq.rest.sqs.TheSQSRestServerBuilder$$anon$1.action(SQSRestServerBuilder.scala:89)
	at org.elasticmq.rest.sqs.CreateQueueDirectives$class.$init$(CreateQueueDirectives.scala:19)
	at org.elasticmq.rest.sqs.TheSQSRestServerBuilder$$anon$1.<init>(SQSRestServerBuilder.scala:89)
	at org.elasticmq.rest.sqs.TheSQSRestServerBuilder.start(SQSRestServerBuilder.scala:89)

when I use this line in my test:

val server = SQSRestServerBuilder.start()

The below is how the shapeless library is imported via spray-routing-shapeless2_2.11:1.3.3. There is no other mention of shapeless in the dependency tree except here:

[0m[[0minfo[0m] [0m  +-io.spray:spray-json_2.11:1.3.2 [S][0m
[0m[[0minfo[0m] [0m  +-io.spray:spray-routing-shapeless2_2.11:1.3.3 [S][0m
[0m[[0minfo[0m] [0m    +-com.chuusai:shapeless_2.11:2.1.0 [S][0m
[0m[[0minfo[0m] [0m    +-io.spray:spray-http_2.11:1.3.3 [S][0m
[0m[[0minfo[0m] [0m    | +-io.spray:spray-util_2.11:1.3.3 [S][0m
[0m[[0minfo[0m] [0m    | +-org.parboiled:parboiled-scala_2.11:1.1.7 [S][0m
[0m[[0minfo[0m] [0m    |   +-org.parboiled:parboiled-core:1.1.7[0m

Im using Spray 1.3.3, akka 2.3.11, aws-sdk 1.10.0.

Is this something that anyone has experienced?

**Comment by adamw** [comment]
hmm, "interesting" :) Just in case, I uploaded 2.3.9-SNAPSHOT which depends on akka 2.3.11 and aws-sdk 1.10.1. Can you try that? 

This shouldn't really change anything as spray is the same, but who knows ;)

There's no other root cause exceptions further down the stack trace?

**Comment by spiritedtechie** [comment]
So I have managed to work around the problem by not using spray-routing-shapeless, and just using spray-routing. This seems to remove the shapeless 2.1.0 dependency and I end up with shapeless 1.2.4 on my classpath (transitive dependency of spray-routing (non shapeless)). This seems to work.

**Comment by adamw** [comment]
Ah, so 1.2.4 was evicted by 2.1.0. Soon I hope to move to akka-http which I think doesn't depend on shapeless, or at least on a newer one :)

**Comment by adamw** [comment]
0.9.0-beta1 now uses akka-http (https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-0.9.0-beta1.jar)
