### ISSUE TITLE
Queue names are not limited to 80 characters

### ISSUE THREAD

**Issue by conniec** [adamw/elasticmq#58]
Queue names are limited to 80 characters. Alphanumeric characters plus hyphens (-) and underscores (_) are allowed.

There should be some more validation on the SQS queue name when creating a queue. 

https://aws.amazon.com/sqs/faqs/

**Comment by conniec** [comment]
hey @adamw will this be released in the next version? thanks!

**Comment by adamw** [comment]
Released 0.8.12 :)

**Comment by conniec** [comment]
awesome thanks! :)
