### ISSUE TITLE
Ho to start elasticmq server with preexisting queue or to be created queue at first request form CLI?

### ISSUE THREAD

**Issue by CyborTronik** [adamw/elasticmq#60]
I'm starting elaticmq server from cli like: java -jar ....
I would like to specify in conf file which queue should exists (and to be created automatically, useful for  deploy&redeploy, testing and so on). Or a way to say to server to create a queue at first request.
Thanks

**Comment by adamw** [comment]
That's not possible currently - but would be quite easy to implement, if you'd like to take a shot.

**Comment by luispabon** [comment]
This would be a great, basic feature to have. Our dev boxes init scripts for elasticmq have some ugly sleeps to wait until it's ready, then creating the queues via curl.

**Comment by adamw** [comment]
Can you try the 0.9.0-beta1 release (https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-0.9.0-beta1.jar)? It has a new config parameter (described in the readme) which allows you to create queues on startup

**Comment by farvour** [comment]
@adamw thank you for this. I was also banging my head with the `queues {}` configuration not doing anything with 0.8. I will try the `0.9.0` series.

**Comment by paul-cummings** [comment]
I have a .sh script for creating SQS queues, is it possible to use this to create SQS queues on startup with Elasticmq?
