### ISSUE TITLE
Increase maximum message size to 256kb

### ISSUE THREAD

**Issue by mrwiggles** [adamw/elasticmq#62]
As detailed here https://aws.amazon.com/about-aws/whats-new/2013/06/18/amazon-sqs-announces-256KB-large-payloads/, the maximum payload for SQS messages and batches is 256k, up from the previous 64k.  

It would be useful to have elasticmq updated to honor this limit as well.

**Comment by mrwiggles** [comment]
PR issue at https://github.com/adamw/elasticmq/pull/63

**Comment by adamw** [comment]
Thanks! Released in 0.9.0-beta1
