### ISSUE TITLE
SQS short polling not possible in strict mode?

### ISSUE THREAD

**Issue by Nakiami** [adamw/elasticmq#70]
Hi,

it does not seem possible to send a WaitTimeSeconds of 0 when receiving a message from a queue.

In the [SQS documentation](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-long-polling.html) it states that

> Short polling occurs when the WaitTimeSeconds parameter of a ReceiveMessage call is set to 0. This happens in one of two ways – either the ReceiveMessage call sets WaitTimeSeconds to 0, or the ReceiveMessage call doesn’t set WaitTimeSeconds and the queue attribute ReceiveMessageWaitTimeSeconds is 0.

But in ElasticMQ, when in strict mode, we seem to be enforcing values between and including 1 and 20. Example: https://github.com/adamw/elasticmq/blob/161eae5f6b828bfb4445d41e25d5cc34430a6614/rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/SQSRestServerBuilder.scala#L370

Is this intended behavior?

Some libraries, like [spring-cloud-aws](http://cloud.spring.io/spring-cloud-aws/) defaults to 0 WaitTimeSeconds on receive, and cannot be easily changed for some methods. The workaround for using spring-cloud-sqs seems to be to disable strict mode in ElasticMQ.

**Comment by adamw** [comment]
Can you try version 0.9.2-SNAPSHOT, https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-0.9.2-SNAPSHOT.jar ?

**Comment by adamw** [comment]
Thanks for reporting, if the SQS spec says otherwise it's definitely not intended behavior :)

**Comment by Nakiami** [comment]
0.9.2-SNAPSHOT works as expected, thanks!

**Comment by adamw** [comment]
Great, 0.9.2 released :)
