### ISSUE TITLE
CreateQueue fails when attributes aren't passed but are changed from default

### ISSUE THREAD

**Issue by dr3s** [adamw/elasticmq#85]
https://github.com/adamw/elasticmq/blob/master/rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/CreateQueueDirectives.scala#L47

CreateQueue doesn't take into consideration when attributes aren't passed in the request but have been changed from the defaults.  This differs from AWS SQS behavior.  If attributes aren't passed, they should not be considered in determining whether the queue name exists exception is thrown.

**Comment by adamw** [comment]
Ah :) maybe you could try writing a PR? thanks!
