### ISSUE TITLE
Support for dynamic port

### ISSUE THREAD

**Issue by pjungermann** [adamw/elasticmq#88]
This issue is related to #87 

Instead of using the default port, it would be great to support a dynamic port. I tried that by using port 0 and then retrieve the actual port from the started `SQSRestServer` instance, but due to #87, the queue addresses have been wrong and due to the fact that the `NodeAddress` is just some kind of string builder, using port 0 at the `serverAddress` just resulted in port 0 being part of the string.

A workaround here is to find a free socket yourself by i.e. using `new ServerSocker(0).getLocalPort`. For development, that was fine (so far), but there are concurrency issues as other process might bind to the port you have found to be free. Therefore, it was failing on our CI server. But exactly there, we would need that dynamic port feature to allow multiple test runs using ElasicMQ, e.g. feature branches or different projects.

**Comment by nebnagrom** [comment]
I found it unclear how to get the port from the started server, for anyone else who tries to do this you'll need to wait for the server to start with something like this (Java):
`startedServer.waitUntilStarted().localAddress().getPort()`

**Comment by adamw** [comment]
@nebnagrom maybe you could create a PR and add this info to the readme?
