### ISSUE TITLE
Support for dead letter queues

### ISSUE THREAD

**Issue by hexdigest** [adamw/elasticmq#90]
Hi, do you plan to add support of Dead Letter Queues (deadLetterTargetArn attribute for CreateQueue)?

**Comment by adamw** [comment]
No specific plans but always happy to accept PRs :)

**Comment by mkorolyov** [comment]
Hi, working on it right now, just wanted to sync if anyone doing or going to do the same not to waste time.

**Comment by mkorolyov** [comment]
seems this one could be closed. was done in #91

**Comment by adamw** [comment]
Ah yes :)
